//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_SETTINGS
    {
        public string AC_ACCOUNT { get; set; }
        public decimal SQ_ACCOUNT_SETTING_VERSION { get; set; }
        public string AC_ACCOUNT_TYPE { get; set; }
        public string DS_ACCOUNT { get; set; }
        public string AC_DEFAULT_IBAN { get; set; }
        public Nullable<decimal> AM_CHEQUE_LIMIT { get; set; }
        public System.DateTime DT_SETTING_VALID_FROM { get; set; }
        public System.DateTime DT_SETTING_VALID_TO { get; set; }
        public System.DateTime DT_VALID_FROM { get; set; }
        public System.DateTime DT_VALID_TO { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
