//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALANCE
    {
        public string AC_ACCOUNT { get; set; }
        public string AC_BALANCE_TYPE { get; set; }
        public string AC_BALANCE_SUBTYPE { get; set; }
        public decimal YD_BALANCE { get; set; }
        public decimal MD_BALANCE { get; set; }
        public decimal AM_INITIAL_DEBIT { get; set; }
        public decimal AM_FINAL_DEBIT { get; set; }
        public decimal AM_MONTH_DEBIT { get; set; }
        public decimal AM_INITIAL_CREDIT { get; set; }
        public decimal AM_FINAL_CREDIT { get; set; }
        public decimal AM_MONTH_CREDIT { get; set; }
        public string AC_CURRENCY { get; set; }
        public decimal NI_TRANSACTION { get; set; }
        public string AC_BALANCE_STATUS { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
