//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE
    {
        public string AC_CHEQUE_ZIB { get; set; }
        public string AC_CHEQUE_ACCOUNT_NUMBER { get; set; }
        public string AC_CHEQUE_NUMBER { get; set; }
        public decimal SQ_CHEQUE_VERSION { get; set; }
        public decimal SQ_OPERATION { get; set; }
        public decimal AM_CHEQUE { get; set; }
        public string AC_CURRENCY { get; set; }
        public string AC_ORIGINAL_CHEQUE_ZIB { get; set; }
        public string AC_ORIGINAL_CHEQUE_ACCT_NUMBER { get; set; }
        public string AC_ORIGINAL_CHEQUE_NUMBER { get; set; }
        public string AC_ORIGIN_CASHIER_ACCOUNT { get; set; }
        public string AC_DESTINATION_CASHIER_ACCOUNT { get; set; }
        public decimal NI_CHEQUE_SUBSTITUTIONS { get; set; }
        public string AC_CHEQUE_STATUS { get; set; }
        public string AC_CHEQUE_STATUS_MOTIVE { get; set; }
        public Nullable<decimal> SQ_OBSERVATION { get; set; }
        public bool FG_CURRENT_VERSION { get; set; }
        public Nullable<System.DateTime> DT_VALID_FROM { get; set; }
        public Nullable<System.DateTime> DT_VALID_TO { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
