//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATION
    {
        public decimal SQ_OPERATION { get; set; }
        public string AC_OPERATION_TYPE { get; set; }
        public System.DateTime DT_OPERATION { get; set; }
        public string AC_OPERATION_STATUS { get; set; }
        public Nullable<decimal> AM_OPERATION { get; set; }
        public Nullable<decimal> SQ_OBSERVATION { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
