//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLICY_HOLDER
    {
        public decimal SQ_POLICY_HOLDER { get; set; }
        public string AC_POLICY_NUMBER { get; set; }
        public string DS_PARTNER_NAME { get; set; }
        public string AC_NIF { get; set; }
        public Nullable<System.DateTime> DT_BIRTH { get; set; }
        public string AC_POLICY_HOLDER_TYPE { get; set; }
        public string AC_PROFESSION_CODE { get; set; }
        public string DS_PROFESSION { get; set; }
        public Nullable<System.DateTime> DT_UNEMPLOYED { get; set; }
        public string AC_EMPLOYEE_CATEGORY { get; set; }
        public string DS_ADDRESS { get; set; }
        public string DS_LOCATION { get; set; }
        public string DS_POSTAL_CODE { get; set; }
        public string AC_COUNTRY { get; set; }
        public string AC_PHONE_NUMBER { get; set; }
        public string AC_PERSONAL_PHONE_NUMBER { get; set; }
        public string AC_FAX_NUMBER { get; set; }
        public string AC_EMAIL { get; set; }
        public string AC_FISCAL_DOCUMENT_NUMBER { get; set; }
        public Nullable<System.DateTime> DT_FISCAL_DOCUMENT { get; set; }
        public string AC_FICAL_DOCUMENT { get; set; }
        public Nullable<System.DateTime> DT_FISCAL_DOCUMENT_END { get; set; }
        public string AC_NATIONALITY { get; set; }
        public string AC_BANK { get; set; }
        public string AC_OFFICE { get; set; }
        public string AC_NIB { get; set; }
        public string AC_COLLECTION_USER_CODE { get; set; }
        public string AC_MANAGER_USER_CODE { get; set; }
        public string AC_ORIGIN_GROUP { get; set; }
        public Nullable<decimal> NI_DRIVING_LICENSE { get; set; }
        public string DT_DRIVING_LICENSE { get; set; }
        public string DT_DRIVING_LICENSE_END { get; set; }
        public string AC_DRIVING_LICENSE { get; set; }
        public string DS_HISTORY { get; set; }
        public string DS_OBSERVATION { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
