//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT
    {
        public decimal SQ_RECEIPT { get; set; }
        public string AC_COMPANY { get; set; }
        public decimal SQ_OPERATION { get; set; }
        public string AC_OPERATION_TYPE { get; set; }
        public string AC_ORIGINAL_RECEIPT_NUMBER { get; set; }
        public string AC_RECEIPT_TYPE { get; set; }
        public string AC_RECEIPT_SUBTYPE { get; set; }
        public decimal SQ_POLICY_HOLDER { get; set; }
        public string AC_POLICY_NUMBER { get; set; }
        public System.DateTime DT_EMISSION { get; set; }
        public System.DateTime DT_DUE_DATE { get; set; }
        public System.DateTime DT_MATURITY_DATE { get; set; }
        public Nullable<System.DateTime> DT_CANCEL_POLICY { get; set; }
        public string AC_PREMIUM_PERIOD { get; set; }
        public string AC_BRANCH { get; set; }
        public string AC_PRODUCT { get; set; }
        public Nullable<System.DateTime> DT_RISK_BEGIN { get; set; }
        public Nullable<System.DateTime> DT_RISK_END { get; set; }
        public string AC_PROPOSAL_NUMBER { get; set; }
        public string AC_BENEFITS { get; set; }
        public string FG_GROUP_COLLECTION { get; set; }
        public string AC_GROUP_POLICY { get; set; }
        public string AC_LICENSE_PLATE { get; set; }
        public Nullable<System.DateTime> DT_WORK_BEGIN { get; set; }
        public Nullable<System.DateTime> DT_WORK_END { get; set; }
        public Nullable<decimal> NI_WORK_DURATION { get; set; }
        public decimal AM_RECEIPT_TOTAL { get; set; }
        public Nullable<decimal> AM_SIMPLE_PREMIUM { get; set; }
        public Nullable<decimal> AM_COMERCIAL_PREMIUM { get; set; }
        public Nullable<decimal> AM_COMERCIAL_DISCOUNT { get; set; }
        public Nullable<decimal> AM_GREEN_CARD_COSTS { get; set; }
        public Nullable<decimal> AM_RECORD_COST { get; set; }
        public Nullable<decimal> AM_POLICY_COST { get; set; }
        public Nullable<decimal> AM_BONUS_MALUS { get; set; }
        public Nullable<decimal> AM_ASSISTANCE { get; set; }
        public Nullable<decimal> AM_SURCHARGE { get; set; }
        public Nullable<decimal> AM_PREMIUM_CORRECTION { get; set; }
        public string AC_CURRENCY { get; set; }
        public string AC_CLAIM_NUMBER { get; set; }
        public string AC_SUB_CLAIM_NUMBER { get; set; }
        public Nullable<System.DateTime> DT_CLAIM_OCCURRENCE { get; set; }
        public Nullable<System.DateTime> DT_CLAIM_OPENING { get; set; }
        public string AC_CLAIM_DOCUMENT_NUMBER { get; set; }
        public string AC_IDS { get; set; }
        public Nullable<bool> FG_AGGREGATION { get; set; }
        public string AC_AGGREGATION_REFERENCE { get; set; }
        public string AC_ATM_ENTITY { get; set; }
        public string AC_ATM_REFERENCE { get; set; }
        public string AC_CTT_REFERENCE { get; set; }
        public string FG_COLLECT_LETTER_SENT { get; set; }
        public Nullable<short> NI_INSURED_OBJECTS { get; set; }
        public string DS_INSURED_OBJECT { get; set; }
        public string AC_MANAGER_USER_CODE { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
