//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_COLLECTION
    {
        public decimal SQ_RECEIPT { get; set; }
        public string DS_ADDRESS { get; set; }
        public string DS_POSTAL_CODE { get; set; }
        public string DS_CITY_NAME { get; set; }
        public string DS_COUNTY_NAME { get; set; }
        public string AC_COUNTRY { get; set; }
        public string AC_COLLECT_LETTER_TYPE { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
