//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_STATUS
    {
        public decimal SQ_RECEIPT { get; set; }
        public decimal SQ_RECEIPT_VERSION { get; set; }
        public decimal SQ_OPERATION { get; set; }
        public string AC_OPERATION_TYPE { get; set; }
        public string AC_BRANCH { get; set; }
        public string AC_PRODUCT { get; set; }
        public string AC_POLICY_NUMBER { get; set; }
        public string AC_ORIGINAL_PAYMENT_TYPE { get; set; }
        public string AC_PAYMENT_TYPE { get; set; }
        public string AC_CLAIM_NUMBER { get; set; }
        public string AC_RECEIPT_STATUS { get; set; }
        public string AC_RECEIPT_STATUS_MOTIVE { get; set; }
        public Nullable<decimal> SQ_OBSERVATION { get; set; }
        public string AC_OPERATION_ACCOUNT { get; set; }
        public string AC_IBAN { get; set; }
        public string AC_EXTERNAL_REFERENCE { get; set; }
        public bool FG_CURRENT_VERSION { get; set; }
        public System.DateTime DT_VALID_FROM { get; set; }
        public System.DateTime DT_VALID_TO { get; set; }
        public string AC_COLLECTION_USER_CODE { get; set; }
        public string AC_BIC { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
