//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSLWebProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION_DETAIL
    {
        public decimal SQ_TRANSACTION { get; set; }
        public string AC_ACCOUNT { get; set; }
        public string AC_COMPANY { get; set; }
        public string AC_BALANCE_TYPE { get; set; }
        public string AC_BALANCE_SUBTYPE { get; set; }
        public decimal SQ_OPERATION { get; set; }
        public string AC_OPERATION_TYPE { get; set; }
        public Nullable<System.DateTime> DT_TRANSACTION { get; set; }
        public string AC_CREDIT_DEBIT { get; set; }
        public Nullable<decimal> AM_TRANSACTION { get; set; }
        public string AC_CURRENCY { get; set; }
        public string AC_POLICY_NUMBER { get; set; }
        public string AC_CLAIM_NUMBER { get; set; }
        public string AC_ORIGINAL_RECEIPT_NUMBER { get; set; }
        public Nullable<decimal> SQ_RECEIPT { get; set; }
        public string AC_CREATION_USER { get; set; }
        public System.DateTime TS_CREATION { get; set; }
        public string AC_LAST_UPDATE_USER { get; set; }
        public System.DateTime TS_LAST_UPDATE { get; set; }
    }
}
